### ISSUE TITLE
index.html expansion

### ISSUE THREAD

**Issue by Anna-Janina** [GarrettChaney/superhero-smackdown#15]
As a user, I want to have a polished and refined experience when viewing the website on various types of devices, so that I can access and use the website comfortably no matter what device I am using.

When visiting the website on different types of devices, the website should automatically adjust its layout and design to fit the size and resolution of the device. This includes adjusting the size of text and buttons, rearranging elements to fit the screen, and hiding certain elements that are not essential to the user experience on smaller devices.

Acceptance Criteria:

- When viewing the website on a desktop computer, the layout and design should be optimized for larger screens.
- When viewing the website on a tablet, the layout and design should be optimized for the smaller screen size.
- When viewing the website on a mobile phone, the layout and design should be optimized for the even smaller screen size.
- The text and buttons should be legible and easy to interact with on all devices.
- Elements that are not essential to the user experience on smaller screens should be hidden.
- The website should retain a polished and refined look and feel on all devices.

**Comment by GarrettChaney** [comment]
Completed.
