### ISSUE TITLE
base/local-storage

### ISSUE THREAD

**Issue by NealeAust** [GarrettChaney/superhero-smackdown#18]
As a developer I want to create local storage functionality whereby details of Marvel Superhero battles are automatically stored.

The web application should include a Fight History page that displays a list of battles conducted, including the Marvel Superheroes name and the winner's name.  A user requires the ability that upon clicking on a clear history button all stored data is cleared. 

### User Acceptance

- When I complete a Marvel Superhero battle

- Details of the contestants and the winner are automatically saved into local storage

- A history of battles is displayed on the Fight History page

- By clicking on the 'Clear History' button I can clear all data stored in local storage.

**Comment by GarrettChaney** [comment]
Completed
