### ISSUE TITLE
results.html

### ISSUE THREAD

**Issue by Anna-Janina** [GarrettChaney/superhero-smackdown#23]
As a developer, I want to create the styling (bulma) of the results.html page so that other team mates can test their JavaScript code (2 hero's fighting again each other).
The developer should create:
- main container with a big box (picture of the winner)
- a footer with a button
- if applicable CSS styling
- HTML structure should be clear, clean and properly formatted
- Basic layout should be responsive and compatible with different browser

As a user, I want to see which hero won the fight on different types of devices.

**Comment by GarrettChaney** [comment]
Completed.
