### ISSUE TITLE
Update index.html

### ISSUE THREAD

**Issue by Anna-Janina** [GarrettChaney/superhero-smackdown#34]
As a developer, I want to update the bulma/css styling of the results.html page.
The developer should create:
- Change white button to yellow button
- When hover over button, the button should be orange
- Link smackdown history to page 3

As a user, I want to see a fun colourful balanced UI. When I click on to smackdown history, it should take me to the history. If I select one hero that button should have a different colour.

**Comment by GarrettChaney** [comment]
Completed
